module.exports = {
  rules: {
    'no-new': 0,
    'no-debugger': 0,
    'no-console': 0,
    'no-alert': 0,
    'no-param-reassign': 2, // 禁止在函数内部重新赋值或修改函数参数
    'no-plusplus': 0,
    'no-unused-vars': 1,
    'no-nested-ternary': 2, // 禁止使用嵌套的三元表达式
    'no-underscore-dangle': 0,
    'no-tabs': 0,
    'no-multi-assign': 0,
    'no-extra-boolean-cast': 1,
    'no-else-return': 1, // 禁止在 if 语句中使用 else 分支，当 if 分支中包含 return 语句时
    'no-array-constructor': 0,
    'no-caller': 2,
    'no-cond-assign': ['warn', 'always'],
    'no-const-assign': 2,
    'no-control-regex': 0,
    'no-delete-var': 2,
    'no-dupe-args': 2,
    'no-dupe-class-members': 2,
    'no-dupe-keys': 2, // 禁止在对象字面量中出现重复的键
    'no-duplicate-case': 2, // 禁止在 switch 语句中出现重复的 case 值
    'no-empty-character-class': 'warn',
    'no-empty-pattern': 2,
    'no-eval': 2, // 禁止使用 eval() 函数
    'no-ex-assign': 'warn',
    'no-extend-native': 'warn',
    'no-extra-bind': 'warn',
    'no-extra-label': 'warn',
    'no-fallthrough': 'warn', // 禁止switch case穿透
    'no-func-assign': 'warn',
    'no-implied-eval': 'warn',
    'no-invalid-regexp': 'warn',
    'no-iterator': 'warn',
    'no-return-assign': 2,
    'no-label-var': 'warn',
    'no-labels': ['warn', { allowLoop: true, allowSwitch: false }],
    'no-lone-blocks': 'warn',
    'no-loop-func': 'warn',
    'no-return-await': 2, // 禁止在 async function 中使用不必要的 return await
    'no-mixed-operators': [
      'warn',
      {
        groups: [
          ['&', '|', '^', '~', '<<', '>>', '>>>'],
          ['==', '!=', '===', '!==', '>', '>=', '<', '<='],
          ['&&', '||'],
          ['in', 'instanceof'],
        ],
        allowSamePrecedence: false,
      },
    ],
    'no-multi-str': 'warn',
    'no-native-reassign': 'warn',
    'no-negated-in-lhs': 'warn',
    'no-new-func': 'warn',
    'no-new-object': 'warn',
    'no-new-symbol': 'warn',
    'no-new-wrappers': 'warn',
    'no-obj-calls': 'warn',
    'no-octal': 'warn',
    'no-octal-escape': 'warn',
    'no-redeclare': 'warn',
    'no-regex-spaces': 'warn',
    'no-restricted-syntax': ['warn', 'WithStatement'],
    'no-script-url': 0,
    'no-self-assign': 'warn',
    'no-self-compare': 'warn',
    'no-sequences': 'warn',
    'no-shadow-restricted-names': 'warn',
    'no-sparse-arrays': 'warn',
    'no-template-curly-in-string': 'warn',
    'no-this-before-super': 'warn',
    'no-throw-literal': 'warn',
    'no-undef': 'error',
    // 'no-restricted-globals': ['error'].concat(restrictedGlobals),
    'no-unexpected-multiline': 'warn',
    'no-unreachable': 'warn',
    'no-unused-expressions': 0,
    'no-unused-labels': 'warn',
    'no-use-before-define': [
      'warn',
      {
        functions: false,
        classes: false,
        variables: false,
      },
    ],
    'no-useless-computed-key': 'warn',
    'no-useless-concat': 'warn',
    'no-useless-constructor': 'warn',
    'no-useless-escape': 'warn',
    'no-useless-rename': [
      'warn',
      {
        ignoreDestructuring: false,
        ignoreImport: false,
        ignoreExport: false,
      },
    ],
    'no-with': 'warn',
    'no-whitespace-before-property': 'warn',
    'no-restricted-properties': [
      'error',
      {
        object: 'System',
        property: 'import',
        message:
          'Please use import() instead. More info: https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#code-splitting',
      },
    ],
    // 一个const，let 定义一个变量
    'one-var': ['warn', 'never'],
    // 不使用 var
    'no-var': 2,
    'no-confusing-arrow': 0,
    'no-trailing-spaces': 0,
  },
}
